export const TEMPLATES = [
  { cat: "Sales", title: "Lead qualification agent", desc: "Scores every new HubSpot lead against your ICP and alerts the owner.", prompt: "Build a lead qualification agent that scores new HubSpot leads against our ICP (company size, industry, role seniority), writes the score back to the CRM, and posts hot leads to Slack.", tools: ["HubSpot", "Slack"] },
  { cat: "Productivity", title: "Meeting brief assistant", desc: "Preps a one-page brief for every meeting on your calendar.", prompt: "Build a meeting assistant agent that reviews my calendar, prepares briefing notes for upcoming meetings, and drafts follow-up emails based on meeting transcripts.", tools: ["Google Calendar", "Gmail"] },
  { cat: "Support", title: "Support ticket triage", desc: "Classifies, prioritises and drafts replies for incoming tickets.", prompt: "Build a support inbox that classifies incoming tickets by urgency and topic, drafts a reply for each using our help-center docs, and escalates angry customers to a human.", tools: ["Gmail", "Knowledge base"] },
  { cat: "Analysts", title: "Vendor comparison scorecard", desc: "Weighted criteria, side-by-side scores, exportable summary.", prompt: "Build a vendor comparison tool where I define evaluation criteria with custom weights, score each vendor, and get an AI-written recommendation summary I can export.", tools: [] },
  { cat: "HR", title: "Candidate screening assistant", desc: "Reads resumes, matches to the role, suggests interview questions.", prompt: "Build a candidate screening app that reads uploaded resumes, scores them against a job description, and suggests tailored interview questions for each candidate.", tools: ["Google Drive"] },
  { cat: "Developers", title: "LangGraph research agent", desc: "Multi-step web research agent with a streaming chat UI.", prompt: "Build a LangGraph research agent that plans search queries, reads sources, and writes a cited report, with a streaming chat UI and a trace view.", tools: ["Web search"] },
  { cat: "Marketing", title: "Content repurposing studio", desc: "Turns one blog post into LinkedIn, X and newsletter drafts.", prompt: "Build a content studio where I paste a blog post and an agent produces LinkedIn, X and newsletter versions in our brand voice, with approval before anything is posted.", tools: ["LinkedIn", "X"] },
  { cat: "Finance", title: "Invoice reconciliation agent", desc: "Matches invoices to payments and flags mismatches.", prompt: "Build an invoice reconciliation agent that matches uploaded invoices to bank transactions from a CSV, flags mismatches, and produces a monthly summary.", tools: ["Google Sheets"] },
  { cat: "Analysts", title: "Market sizing calculator", desc: "Enter assumptions, get TAM/SAM/SOM with a written rationale.", prompt: "I regularly estimate market sizes for technology segments. Build a tool where I enter assumptions like number of potential buyers, average deal size and adoption rate, and it calculates TAM, SAM and SOM with an AI-written rationale I can paste into a report.", tools: [] },
  { cat: "Sales", title: "Meeting follow-up writer", desc: "Turns call notes into a follow-up email and CRM update.", prompt: "After every sales call I paste my rough notes. Build an app where an agent turns them into a polished follow-up email draft, a list of next steps with owners, and a short summary I can log in the CRM.", tools: ["Gmail", "HubSpot"] },
  { cat: "Marketing", title: "SEO brief generator", desc: "Keyword in, a full content brief out.", prompt: "Build a content brief generator: I enter a target keyword and audience, and an agent produces an SEO brief with search intent, an outline with H2/H3s, questions to answer, internal link ideas and a meta description.", tools: ["Web search"] },
  { cat: "Support", title: "Refund request assistant", desc: "Checks policy and drafts a decision for each refund request.", prompt: "Build an app where support agents paste a refund request; an AI checks it against our refund policy, recommends approve / partial / deny with the reason, and drafts the reply — a human always approves before anything is sent.", tools: ["Knowledge base"] },
  { cat: "HR", title: "Onboarding buddy", desc: "A personal first-two-weeks plan for every new hire.", prompt: "Build an onboarding app: HR enters a new hire's role, team and start date, and an agent creates a two-week onboarding plan with daily tasks, people to meet and docs to read, which the new hire can tick off.", tools: ["Google Calendar"] },
  { cat: "Legal", title: "Contract clause reviewer", desc: "Flags risky clauses and suggests safer wording.", prompt: "Build a contract review tool: I upload a contract, an agent extracts key clauses (term, liability, termination, IP, payment), flags anything unusual against our playbook, and suggests safer alternative wording for each flag.", tools: ["Google Drive"] },
  { cat: "Legal", title: "NDA triage agent", desc: "Sorts incoming NDAs into sign / redline / escalate.", prompt: "Build an agent that reviews incoming NDAs every morning, compares them with our standard NDA, and sorts each into 'safe to sign', 'needs redlines' (with suggested edits) or 'escalate to legal'.", tools: ["Gmail"] },
  { cat: "General", title: "Personal research assistant", desc: "Ask a question, get a sourced one-page answer.", prompt: "Build a research assistant where I ask a question, an agent searches the web, reads the best sources and writes a one-page answer with citations, and I can save answers to a personal library.", tools: ["Web search"] },
  { cat: "Productivity", title: "Weekly status digest", desc: "Collects updates and writes the Friday status email.", prompt: "Build an app where my team drops quick weekly updates, and every Friday an agent writes one status digest grouped by project with wins, risks and asks, ready for me to review and send.", tools: ["Slack"] },
  { cat: "Developers", title: "PR review summarizer", desc: "Plain-English summaries and risk notes for every PR.", prompt: "Build a GitHub PR review assistant: for each open pull request an agent writes a plain-English summary, highlights risky changes and missing tests, and suggests review comments I can post.", tools: ["GitHub"] },
] as const;

export const LEARN = [
  { title: "Your first app in 10 minutes", kind: "Tutorial", mins: 10 },
  { title: "Connecting real data: Google, Slack & API keys", kind: "Tutorial", mins: 8 },
  { title: "Builder vs Developer view — when to switch", kind: "Guide", mins: 5 },
  { title: "Bring your own LangGraph or CrewAI agent", kind: "Tutorial", mins: 12 },
  { title: "Guardrails: keeping agents safe with approvals", kind: "Guide", mins: 6 },
  { title: "From preview to production: shipping checklist", kind: "Guide", mins: 7 },
] as const;
